### ISSUE TITLE
[Crash] Energy Reader - Division by Zero

### ISSUE THREAD

**Issue by ReTeYeZ** [SonarSonic/Practical-Logistics-2#13]
_I placed a Node on a Kinetic Dynamo from Immersive Engineering and upon rightclicking an Energy Reader the game crashes (Info Reader works):_

[10:59:23] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121) ~[bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.ArithmeticException: / by zero
	at sonar.logistics.client.gui.GuiEnergyReader.renderInfo(GuiEnergyReader.java:137) ~[GuiEnergyReader.class:?]
	at sonar.logistics.client.gui.GuiEnergyReader.renderInfo(GuiEnergyReader.java:30) ~[GuiEnergyReader.class:?]
	at sonar.logistics.client.gui.generic.GuiSelectionList.func_146979_b(GuiSelectionList.java:109) ~[GuiSelectionList.class:?]
	at sonar.logistics.client.gui.GuiEnergyReader.func_146979_b(GuiEnergyReader.java:85) ~[GuiEnergyReader.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114) ~[bgl.class:?]
	at sonar.logistics.client.gui.generic.GuiSelectionList.func_73863_a(GuiSelectionList.java:133) ~[GuiSelectionList.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) ~[bnz.class:?]
	... 17 more
[10:59:23] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/17/17 10:59 AM
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at sonar.logistics.client.gui.GuiEnergyReader.renderInfo(GuiEnergyReader.java:137)
	at sonar.logistics.client.gui.GuiEnergyReader.renderInfo(GuiEnergyReader.java:30)
	at sonar.logistics.client.gui.generic.GuiSelectionList.func_146979_b(GuiSelectionList.java:109)
	at sonar.logistics.client.gui.GuiEnergyReader.func_146979_b(GuiEnergyReader.java:85)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at sonar.logistics.client.gui.generic.GuiSelectionList.func_73863_a(GuiSelectionList.java:133)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sonar.logistics.client.gui.GuiEnergyReader.renderInfo(GuiEnergyReader.java:137)
	at sonar.logistics.client.gui.GuiEnergyReader.renderInfo(GuiEnergyReader.java:30)
	at sonar.logistics.client.gui.generic.GuiSelectionList.func_146979_b(GuiSelectionList.java:109)
	at sonar.logistics.client.gui.GuiEnergyReader.func_146979_b(GuiEnergyReader.java:85)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at sonar.logistics.client.gui.generic.GuiSelectionList.func_73863_a(GuiSelectionList.java:133)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: sonar.logistics.client.gui.GuiEnergyReader
	Mouse location: Scaled: (180, 119). Absolute: (1080, 720)
	Screen size: Scaled: (360, 240). Absolute: (2160, 1440). Scale factor of 6

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['<PROFILE NAME>'/291, l='MpServer', x=149.20, y=114.63, z=102.78]]
	Chunk stats: MultiplayerChunkCache: 546, 546
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (168,64,160), Chunk: (at 8,4,0 in 10,10; contains blocks 160,0,160 to 175,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 49466 game time, 10267 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 101 total; [EntityCreeper['Creeper'/11011, l='MpServer', x=97.50, y=31.00, z=30.50], EntityZombie['Zombie'/11012, l='MpServer', x=95.50, y=31.00, z=31.50], EntityBat['Bat'/10246, l='MpServer', x=202.73, y=47.44, z=152.55], EntityBat['Bat'/10759, l='MpServer', x=123.54, y=62.05, z=108.19], EntityCreeper['Creeper'/7689, l='MpServer', x=204.81, y=53.00, z=128.50], EntityBat['Bat'/10762, l='MpServer', x=137.74, y=38.02, z=82.55], EntityZombie['Zombie'/8203, l='MpServer', x=154.50, y=15.00, z=172.50], EntityBat['Bat'/10763, l='MpServer', x=135.50, y=36.21, z=75.33], EntityZombie['Zombie'/11275, l='MpServer', x=228.50, y=36.00, z=61.50], EntityWitch['Witch'/6925, l='MpServer', x=179.50, y=18.00, z=142.50], EntityZombie['Zombie'/11278, l='MpServer', x=206.50, y=69.00, z=58.50], EntityCreeper['Creeper'/11279, l='MpServer', x=212.15, y=69.00, z=61.47], EntityZombie['Zombie'/11025, l='MpServer', x=174.50, y=14.00, z=152.50], EntityZombie['Zombie'/10259, l='MpServer', x=82.50, y=27.00, z=54.50], EntityZombie['Zombie'/11028, l='MpServer', x=169.50, y=14.00, z=154.50], EntityBat['Bat'/10005, l='MpServer', x=72.75, y=26.00, z=141.75], EntityCreeper['Creeper'/6434, l='MpServer', x=196.50, y=26.00, z=167.50], EntityBat['Bat'/8994, l='MpServer', x=77.58, y=32.10, z=110.25], EntityPlayerSP['<PROFILE NAME>'/291, l='MpServer', x=149.20, y=114.63, z=102.78], EntitySkeleton['Skeleton'/10276, l='MpServer', x=211.50, y=68.00, z=62.50], EntityCreeper['Creeper'/9510, l='MpServer', x=222.30, y=35.60, z=62.70], EntityBat['Bat'/11046, l='MpServer', x=167.75, y=17.10, z=174.75], EntitySpider['Spider'/10537, l='MpServer', x=116.50, y=36.00, z=79.50], EntitySpider['Spider'/10538, l='MpServer', x=116.50, y=36.00, z=81.50], EntityCreeper['Creeper'/10540, l='MpServer', x=120.50, y=36.00, z=78.50], EntityLatchedRenderer['unknown'/304, l='MpServer', x=149.20, y=114.63, z=102.78], EntityCow['Cow'/55, l='MpServer', x=83.16, y=72.00, z=62.55], EntityCow['Cow'/56, l='MpServer', x=94.23, y=82.00, z=57.51], EntityCow['Cow'/57, l='MpServer', x=94.45, y=80.00, z=55.23], EntityCow['Cow'/58, l='MpServer', x=90.48, y=77.00, z=66.80], EntityZombie['Zombie'/10046, l='MpServer', x=125.50, y=62.00, z=105.50], EntityBat['Bat'/11073, l='MpServer', x=158.99, y=19.05, z=172.47], EntitySkeleton['Skeleton'/9287, l='MpServer', x=76.50, y=27.00, z=67.50], EntitySkeleton['Skeleton'/9032, l='MpServer', x=114.50, y=50.00, z=80.50], EntityEnderman['Enderman'/9289, l='MpServer', x=220.36, y=14.00, z=118.50], EntityCow['Cow'/86, l='MpServer', x=121.50, y=83.00, z=61.50], EntityCow['Cow'/87, l='MpServer', x=120.50, y=83.00, z=61.50], EntityCow['Cow'/88, l='MpServer', x=120.50, y=82.00, z=59.50], EntityCow['Cow'/89, l='MpServer', x=120.50, y=84.00, z=64.50], EntitySheep['Sheep'/90, l='MpServer', x=115.74, y=71.00, z=135.46], EntityZombie['Zombie'/10586, l='MpServer', x=81.50, y=57.00, z=144.50], EntityCreeper['Creeper'/10589, l='MpServer', x=224.50, y=63.00, z=64.50], EntityBat['Bat'/9311, l='MpServer', x=212.53, y=52.08, z=127.99], EntityZombie['Zombie'/11360, l='MpServer', x=186.50, y=20.00, z=175.50], EntitySkeleton['Skeleton'/10850, l='MpServer', x=98.50, y=39.00, z=142.50], EntityCreeper['Creeper'/10851, l='MpServer', x=98.50, y=39.00, z=143.50], EntitySheep['Sheep'/103, l='MpServer', x=123.80, y=71.00, z=114.67], EntitySheep['Sheep'/104, l='MpServer', x=141.46, y=70.00, z=119.00], EntitySheep['Sheep'/105, l='MpServer', x=132.39, y=70.00, z=123.23], EntitySkeleton['Skeleton'/10093, l='MpServer', x=99.50, y=38.00, z=148.50], EntitySkeleton['Skeleton'/10094, l='MpServer', x=98.50, y=38.00, z=147.50], EntitySpider['Spider'/9328, l='MpServer', x=184.50, y=42.00, z=123.50], EntityBat['Bat'/9840, l='MpServer', x=176.36, y=40.00, z=142.55], EntitySquid['Squid'/10100, l='MpServer', x=154.44, y=60.00, z=39.86], EntitySquid['Squid'/10101, l='MpServer', x=153.10, y=59.00, z=46.15], EntityCow['Cow'/120, l='MpServer', x=152.15, y=62.11, z=64.89], EntityCow['Cow'/121, l='MpServer', x=147.50, y=70.00, z=71.50], EntityCow['Cow'/122, l='MpServer', x=146.50, y=72.00, z=72.94], EntityCow['Cow'/125, l='MpServer', x=148.33, y=71.00, z=150.55], EntityCow['Cow'/126, l='MpServer', x=149.49, y=71.00, z=155.09], EntityCow['Cow'/127, l='MpServer', x=151.49, y=68.00, z=152.68], EntityCow['Cow'/128, l='MpServer', x=157.25, y=65.00, z=140.19], EntityZombie['Zombie'/7810, l='MpServer', x=200.73, y=48.00, z=155.30], EntityCreeper['Creeper'/10884, l='MpServer', x=208.50, y=48.00, z=148.50], EntityCreeper['Creeper'/10885, l='MpServer', x=207.50, y=48.00, z=148.50], EntityZombie['Zombie'/10886, l='MpServer', x=204.50, y=48.00, z=153.50], EntityCreeper['Creeper'/10887, l='MpServer', x=204.50, y=48.00, z=155.50], EntityCreeper['Creeper'/11155, l='MpServer', x=214.50, y=45.00, z=59.50], EntitySheep['Sheep'/153, l='MpServer', x=210.48, y=70.00, z=152.77], EntitySheep['Sheep'/154, l='MpServer', x=204.82, y=71.00, z=155.73], EntitySheep['Sheep'/155, l='MpServer', x=203.22, y=71.00, z=157.81], EntitySheep['Sheep'/156, l='MpServer', x=182.78, y=71.00, z=157.46], EntitySheep['Sheep'/157, l='MpServer', x=198.21, y=67.00, z=175.36], EntitySheep['Sheep'/158, l='MpServer', x=194.64, y=67.00, z=175.49], EntitySheep['Sheep'/159, l='MpServer', x=194.49, y=68.00, z=171.76], EntitySheep['Sheep'/160, l='MpServer', x=195.66, y=67.00, z=174.74], EntityItem['item.item.DataCable'/11168, l='MpServer', x=152.12, y=104.00, z=101.03], EntityCreeper['Creeper'/7841, l='MpServer', x=132.50, y=34.00, z=71.50], EntityBat['Bat'/10659, l='MpServer', x=82.82, y=51.24, z=48.50], EntityZombie['Zombie'/11432, l='MpServer', x=102.50, y=46.00, z=89.50], EntityCreeper['Creeper'/9131, l='MpServer', x=195.50, y=43.00, z=118.50], EntitySkeleton['Skeleton'/10924, l='MpServer', x=94.50, y=22.00, z=73.50], EntityBat['Bat'/11441, l='MpServer', x=191.94, y=19.29, z=118.50], EntityBat['Bat'/11442, l='MpServer', x=195.80, y=19.08, z=116.89], EntitySkeleton['Skeleton'/8115, l='MpServer', x=129.50, y=34.00, z=72.50], EntitySkeleton['Skeleton'/11462, l='MpServer', x=160.50, y=17.00, z=169.50], EntitySkeleton['Skeleton'/10187, l='MpServer', x=170.50, y=14.00, z=156.50], EntityItem['item.item.DataCable'/9678, l='MpServer', x=152.59, y=106.00, z=103.00], EntityCreeper['Creeper'/9428, l='MpServer', x=191.50, y=20.00, z=126.50], EntitySkeleton['Skeleton'/8920, l='MpServer', x=225.50, y=36.00, z=64.50], EntityZombie['Zombie'/10978, l='MpServer', x=103.42, y=32.00, z=35.80], EntityZombie['Zombie'/10979, l='MpServer', x=101.50, y=31.00, z=37.50], EntityBat['Bat'/11236, l='MpServer', x=108.59, y=43.81, z=90.37], EntityWitch['Witch'/11497, l='MpServer', x=191.50, y=27.00, z=165.50], EntitySkeleton['Skeleton'/11498, l='MpServer', x=191.50, y=27.00, z=165.50], EntityBat['Bat'/10735, l='MpServer', x=225.21, y=54.23, z=43.31], EntityZombie['Zombie'/7673, l='MpServer', x=102.50, y=47.00, z=87.50], EntityCreeper['Creeper'/7674, l='MpServer', x=101.50, y=47.00, z=88.50], EntityZombie['Zombie'/9724, l='MpServer', x=193.07, y=45.00, z=131.48], EntityBat['Bat'/1534, l='MpServer', x=170.89, y=36.81, z=159.45], EntityZombie['Zombie'/9726, l='MpServer', x=176.50, y=17.00, z=176.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 501380320 bytes (478 MB) / 1498415104 bytes (1429 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.1} [Storage Drawers] (StorageDrawers-1.10.2-3.7.1.jar) 
	UCHIJAAAA	bitdrawers{0.36} [Drawers & Bits] (DrawersBits-1.10.2-0.36.jar) 
	UCHIJAAAA	gravestone{1.4.9} [Gravestone] (GraveStone Mod 1.4.9.jar) 
	UCHIJAAAA	ichunutil{6.3.0} [iChunUtil] (iChunUtil-1.10.2-6.3.0.jar) 
	UCHIJAAAA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	UCHIJAAAA	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	UCHIJAAAA	openglasses{1.4.2} [OC Glasses] (OpenGlasses-1.4.2.jar) 
	UCHIJAAAA	openprinter{0.1.0.5} [OpenPrinter] (OpenPrinter-1.9.4-0.1.0.5.jar) 
	UCHIJAAAA	openradio{0.9.4} [OpenRadio] (OpenRadio-0.9.4-MC1.10.2.jar) 
	UCHIJAAAA	PersistentBits{1.0.6} [Persistent Bits] (PersistentBits-1.10.2-1.0.6.jar) 
	UCHIJAAAA	portalgun{6.0.0} [PortalGun] (PortalGun-1.10.2-6.0.0.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	sonarcore{3.2.6} [SonarCore] (SonarCore-1.10.2-3.2.6.jar) 
	UCHIJAAAA	practicallogistics2{2.0.1} [Practical Logistics 2] (PracticalLogistics2-1.10.2-2.0.1.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4568' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4568, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
[10:59:23] [Server thread/INFO] [FML]: Applying holder lookups
[10:59:23] [Server thread/INFO] [FML]: Holder lookups applied
[10:59:23] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# C:\MultiMC\instances\1.10.2 Factory\minecraft\crash-reports\crash-2017-04-17_10.59.23-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by AEnterprise** [comment]
ah the kinetic dynamo is a funny machine, while it generates energy it has absolutely no internal power buffer, it only outputs the energy it produces but doesn't store any on it's own

**Comment by ReTeYeZ** [comment]
Yeah I figured it might be something like this.
I shoud've mentioned I'm using the version for MC 1.10

**Comment by SonarSonic** [comment]
I've added a >0 check so shouldn't happen again.
