### ISSUE TITLE
Null Pointer Exception (Interact Screen)

### ISSUE THREAD

**Issue by BlayzerQ** [SonarSonic/Practical-Logistics-2#72]
On last version pf PL 1.12
https://paste.dimdev.org/jelebamemu.mccrash

**Comment by douglasg14b** [comment]
Also getting this, can't access the energy reader UI at all :/

**Comment by douglasg14b** [comment]
My error differs somewhat, but it happens when trying to access the energy readers UI when it is connected to a mekanism induction matrix.

```
[14:09:48] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at sonar.logistics.core.tiles.readers.energy.handling.EnergyNetworkHandler.updateInfo(EnergyNetworkHandler.java:31) ~[EnergyNetworkHandler.class:?]
        at sonar.logistics.core.tiles.readers.energy.handling.EnergyNetworkHandler.updateInfo(EnergyNetworkHandler.java:17) ~[EnergyNetworkHandler.class:?]
        at sonar.logistics.base.channels.handling.ListNetworkHandler.updateConnection(ListNetworkHandler.java:82) ~[ListNetworkHandler.class:?]
        at sonar.logistics.base.channels.handling.ListNetworkChannels.updateAllChannels(ListNetworkChannels.java:176) ~[ListNetworkChannels.class:?]
        at sonar.logistics.base.channels.handling.ListNetworkChannels.sendLocalRapidUpdate(ListNetworkChannels.java:192) ~[ListNetworkChannels.class:?]
        at sonar.logistics.core.tiles.readers.base.TileAbstractListReader.sendRapidUpdate(TileAbstractListReader.java:48) ~[TileAbstractListReader.class:?]
        at sonar.logistics.core.tiles.readers.base.TileAbstractListReader.onGuiOpened(TileAbstractListReader.java:68) ~[TileAbstractListReader.class:?]
        at sonar.core.network.FlexibleGuiHandler.openGui(FlexibleGuiHandler.java:117) ~[FlexibleGuiHandler.class:?]
        at sonar.core.network.FlexibleGuiHandler.openBasicMultipart(FlexibleGuiHandler.java:101) ~[FlexibleGuiHandler.class:?]
        at sonar.core.integration.multipart.TileSonarMultipart.openFlexibleGui(TileSonarMultipart.java:92) ~[TileSonarMultipart.class:?]
        at sonar.logistics.core.tiles.base.BlockLogistics.func_180639_a(BlockLogistics.java:54) ~[BlockLogistics.class:?]
        at mcmultipart.api.multipart.IMultipart.onPartActivated(IMultipart.java:261) ~[IMultipart.class:?]
        at mcmultipart.block.BlockMultipartContainer.lambda$onBlockActivated$62(BlockMultipartContainer.java:521) ~[BlockMultipartContainer.class:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_181]
        at mcmultipart.block.BlockMultipartContainer.func_180639_a(BlockMultipartContainer.java:521) ~[BlockMultipartContainer.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by SonarSonic** [comment]
Fixed in dev
