### ISSUE TITLE
Readers and Screens Broken

### ISSUE THREAD

**Issue by mthp1999** [SonarSonic/Practical-Logistics-2#86]
Version: PracticalLogistics2-1.12.2-3.0.8
Forge: forge-14.23.5.2825
SonarCore: Sonar-Core-1.12.2-5.0.19
No Readers will connect to any tile, also whenever anything is connected to a data cable it will delete both the cable and the block connected. 
Basically it just straight up doesn't work.

**Comment by mthp1999** [comment]
Read through the crash logs its giving my server and apparently it is a ticking block entity issue.


-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1842)

-- Block entity being ticked --
Details:
        Name: minecraft:pl2_transfernode // sonar.logistics.core.tiles.nodes.transfer.TileTransferNode
        Block type: ID #2358 (tile.TransferNode // sonar.logistics.core.tiles.nodes.transfer.BlockTransferNode // practicallogistics2:transfernode)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-2637,62,-232), Chunk: (at 3,3,8 in -165,-15; contains blocks -2640,0,-240 to -2625,255,-225), Region: (-6,-1; contains chunks -192,-32 to -161,-1, blocks -3072,0,-512 to -2561,255,-1)
        Actual block type: ID #2358 (tile.TransferNode // sonar.logistics.core.tiles.nodes.transfer.BlockTransferNode // practicallogistics2:transfernode)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1842)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
